### ISSUE TITLE
Add eventsfor begin and end, even if user is just setting the percent

### ISSUE THREAD

**Issue by ajoslin** [driftyco/collide#3]
If the animator is paused and the user sets the percent to 1/0, make some event run.

(?)

**Comment by Ionitron** [comment]
Greetings @ajoslin!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
