### ISSUE TITLE
Make easing curves go backwards properly

### ISSUE THREAD

**Issue by ajoslin** [driftyco/collide#4]
If I'm going backwards from 1 to 0 and am at 0.25, my easing curve should give me a result like I'm 75% of the way to my destination. It shouldn't give me a result like I'm 25% of the way.

**Comment by Ionitron** [comment]
Greetings @ajoslin!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
