### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by mliu95** [driftyco/collide#7]
Hello, I couldn't seem to find a license for this library.

**Comment by marcj** [comment]
+1

**Comment by Ionitron** [comment]
Greetings @mliu95!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
